### ISSUE TITLE
Cannot download DATA and Models

### ISSUE THREAD

**Issue by HyunsooCha** [sbharadwajj/flare#11]
Hi,

Thank you for your great work.
I tried to download data and models that was released last week, but I cannot download those stuffs.
Is there any alternative way to download these things?
or can you fix the link?

Thanks in advance.

**Comment by sbharadwajj** [comment]
Hi!
What problem did you face?
You need to register on the website and login to the page to download. Did you do that?

**Comment by HyunsooCha** [comment]
Yes, I registered and logined website. 
When I click download, the following appears:
![Screenshot from 2024-12-12 22-46-07](https://github.com/user-attachments/assets/96aefccb-6c98-46e4-8d21-70707abdf6b3)

**Comment by sbharadwajj** [comment]
I will check the permissions

**Comment by sbharadwajj** [comment]
Hi,
Its fixed.
Please let me know if the download is successful.

**Comment by HyunsooCha** [comment]
Yeah now it works.
Thanks a lot.
