### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by YiChenCityU** [sbharadwajj/flare#2]
Training Deformer
STAGE 1: Using positional encoding (NeRF) for intrinsic materials
{'material_mlp_ch': 5, 'light_mlp_ch': 3, 'material_mlp_dims': [128, 128, 128, 128], 'light_mlp_dims': [64, 64]}
----------------------------------------------------------------------------------------------------
Re-initializing main() because the training of light MLP diverged and all the values are zero.

I got this error when running the code. Could you give some suggestions? Thanks very much.

**Comment by sbharadwajj** [comment]
Hi,

The training must have automatically restarted correct? 

We don’t use an activation function for the last layer of the light MLP and this causes the training to diverge sometimes. 

Simply restarting the training should work. The code must restart by default.
