### ISSUE TITLE
The role of 'map2_flame_original' argument in forward_pts_batch?

### ISSUE THREAD

**Issue by justin4ai** [sbharadwajj/flare#9]
Dear authors,

Hello, first of all I really appreciate you provide the world with such an amazing project!
I have one question with one line of code about 'Deformation of canonical mesh' section:

```python
            deformed_vertices = FLAMEServer.forward_pts_batch(pnts_c=batched_verts, betas=views_subset["flame_expression"], transformations=transformations, pose_feature=pose_features, 
                                                shapedirs=shapedirs, posedirs=posedirs, lbs_weights=lbs_weights, dtype=torch.float32, map2_flame_original=True)
```
In the code above, the argument 'map2_flame_original' is set as True.

```python
    def forward_pts_batch(self, pnts_c, betas, transformations, pose_feature, shapedirs, posedirs, lbs_weights, dtype=torch.float32, map2_flame_original=True):
        assert len(pnts_c.shape) == 3
        batch_size, num_points, dim = pnts_c.shape
        betas = betas.unsqueeze(1).repeat(1, num_points, 1)
        pose_feature = pose_feature.unsqueeze(1).repeat(1, num_points, 1)
        transformations = transformations.unsqueeze(1).repeat(1, num_points, 1, 1, 1)

        if map2_flame_original:
            pnts_c_original = inverse_pts_batch(pnts_c, self.canonical_exp.unsqueeze(0).repeat(batch_size, num_points, 1), 
                                          self.canonical_transformations.unsqueeze(0).repeat(batch_size, num_points, 1, 1, 1), 
                                          self.canonical_pose_feature.unsqueeze(0).repeat(batch_size, num_points, 1), shapedirs, posedirs, lbs_weights, dtype=dtype)
            pnts_p = forward_pts_batch(pnts_c_original, betas, transformations, pose_feature, shapedirs, posedirs, lbs_weights, dtype=dtype)
        else:    
            pnts_p = forward_pts_batch(pnts_c, betas, transformations, pose_feature, shapedirs, posedirs, lbs_weights, dtype=dtype)

        return pnts_p
```

And seemingly with the argument being True, you do ,,inverse_pts_batch'' before recursively forwarding the points.
But I don't understand why that is needed although the input points, mesh.vertices, are already in a canonical space without any pose or expression. Could you explain why you need to operate inverse function with already canonical vertices?

Best,
Junyeong Ahn

**Comment by sbharadwajj** [comment]
Hi Junyeong,

We dont have precise control over the expression or pose of the canonical mesh that we optimize for as you say "are already in a canonical space without any pose or expression". Thus, using `map2_flame_original`, we map `pnts_c` which are the mesh vertices that we are optimizing for to a canonical pose (jaw open) and mean expression which is defined as `self.canonical_**` [here](https://github.com/sbharadwajj/flare/blob/1c2b6ce358656de3370f414da305753b4eacf2c7/train.py#L408). We want all the deformed expressions to be mapped to this canonical space which has a neutral expression/pose so that it helps the model converge. We keep the jaw open, so it is easier to learn the mouth interior. 

I hope this answers your question.

Regards,
Shrisha

**Comment by justin4ai** [comment]
@sbharadwajj Thanks for your kind explanation! I understand we want to get any status of mesh to a canonical one for the deformation. But the thing is ```mesh.vertices``` are already in canonical space as fas as I understand because of the following line of code:

```python
mesh = flame_canonical_mesh.with_vertices(canonical_offset_vertices)
```

Vertices of ```mesh``` are already updated with canonical_offset_vertices then fed to ```.forward_pts_batch``` with ```map2_flame_original``` that is trivial in my opinion since we don't have to set a canonical mesh back to a canonical mesh that is redundant.

In each iteration, starting from #update/displace vertices# section, 1) mesh is initialized with ```mesh = flame_canonical_mesh.with_vertices(canonical_offset_vertices)``` which means mesh is in a canonical space due to the update with offsets 2) vertices of the mesh are fed to ```FLAMEServer.forward_pts_batch()```. Seemingly each iteration is independent for ```mesh``` so I see those process as just doing redundant works on and on.

Would you specify the errors in my understand? Thanks!

**Comment by sbharadwajj** [comment]
Hi,

You are correct that `flame_canonical_mesh` is already in canonical expression and pose space during the start of the optimization. But we found that the optimization of mesh vertices was highly unstable and diverged quite easily. So, the vertices that we are mapping back to canonical expression and pose space is not `flame_canonical_mesh` (which does not have the exact shape of the subject), but the canonical that we optimize for (flame_canonical_mesh+v_off()). We wanted the "optimized" mesh also to be mapped back to the canonical expression and pose space. I cant recall it exactly now, but I think after we upsample, we updated `flame_canonical_mesh` to the optimized one with specific shape. I suspect that we added the mapping function to help with the optimization after upsampling as well. If I recall correctly, this mapping function makes sure that the expression and pose does not diverge. 

So, it is in the canonical space in 3D, but we want to make sure the expression and pose are also canonical.

**Comment by justin4ai** [comment]
Hi,

So you mean flame_canonical_mesh+v_off() is not guaranteed to be canonical in terms of 'pose and expression' so needed to be mapped back to the canonical 'pose and expression' right? It is in 3D canonical space though.

Then would you let me know what 'shapedirs, posedirs, lbs_weights = deformer_net.query_weights(mesh.vertices)' means? I see shapedirs and posedirs are also fed to the inverse mapping function but cannot understand their exact roles. I know betas and pos_features are what we want to apply to canonical meshes. What is that deformer_net for exactly?

Again really appreciate your help!

Best,
Junyeong Ahn

**Comment by sbharadwajj** [comment]
> So you mean flame_canonical_mesh+v_off() is not guaranteed to be canonical in terms of 'pose and expression' so needed to be mapped back to the canonical 'pose and expression' right? It is in 3D canonical space though

yes exactly. Mapping it back forces it to stay in canonical. 

you can find the lbs function [here](https://github.com/sbharadwajj/flare/blob/1c2b6ce358656de3370f414da305753b4eacf2c7/flame/lbs.py#L25). So if you see, `shapedirs` is the expression blendshapes and `posedirs` are the pose blendshapes, while `lbs_weights` are the linear blend skinning weights. All of these are personalized to the subject.  So the deformer_net learns person-specific blendshapes and lbs weights.

**Comment by justin4ai** [comment]
@sbharadwajj Oh yeah I didn't come up with FLAME itself at the moment. They must be blendshapes with PCA bases. They come from the ```deformer_net``` personalized(I think) to the fitting subject in advance. Eventually the mesh being optimized for the subject is first get back to the canonical expression/pose with them before applying deformation. I hope my understand is right since your kind help and explanation are awesome. Many thanks!

**Comment by sbharadwajj** [comment]
Yes, you are exactly right. Before deforming, they are mapped to the canonical. 
You're welcome.

**Comment by justin4ai** [comment]
@sbharadwajj Hello, can I have one more question?

In [flare](https://github.com/sbharadwajj/flare/tree/master)/[flare](https://github.com/sbharadwajj/flare/tree/master/flare)/[core](https://github.com/sbharadwajj/flare/tree/master/flare/core)
/mesh.py:

```python

    @torch.no_grad()
    def xatlas_uvmap(self):
        import numpy as np
        # Create uvs with xatlas
        v_pos = self.vertices.detach().cpu().numpy()
        t_pos_idx = self.indices.detach().cpu().numpy()
        vmapping, indices, uvs = xatlas.parametrize(v_pos, t_pos_idx)

        # Convert to tensors
        indices_int64 = indices.astype(np.uint64, casting='same_kind').view(np.int64)
        vmapping_int64 = vmapping.astype(np.uint64, casting='same_kind').view(np.int64)
        vmapping = torch.tensor(vmapping_int64, dtype=torch.int64, device=self.device)

        uvs = torch.tensor(uvs, dtype=torch.float32, device=self.device)
        faces = torch.tensor(indices_int64, dtype=torch.int64, device=self.device)

        self._uv_coords = uvs
        self._uv_idx = faces
        self.vmapping = vmapping

```

, you compute the connectivity of the mesh (seemingly for uv-mapping). However, I don't see their usage in any line of code. I might be missing, so would you please let me know what they are for?

Thanks for your help,
Junyeong Ahn

**Comment by sbharadwajj** [comment]
They are used to compute tangent space normals required [here](https://github.com/sbharadwajj/flare/blob/d0e13194772f30961abcd1bbe1e42b4caf0d12bb/flare/modules/neuralshader.py#L101)

**Comment by justin4ai** [comment]
Oh they are here (https://github.com/sbharadwajj/flare/blob/master/flare/core/renderer.py#L125)! I will take a careful look at it. Thanks for helping me out! :)

**Comment by sbharadwajj** [comment]
sure! The code to compute tangent space normals is borrowed from [nvdiffec](https://github.com/NVlabs/nvdiffrec/tree/main). Please check their codebase for details.
